"""Short-term conversation history management for AURA.

Maintains an ordered buffer of turns (User, Assistant, and Tool interactions)
with configurable sliding-window trimming to fit within Large Language Model (LLM) context limits.

Architecture role:
Short-Term Memory stores the immediate, active multi-turn dialogue.
Unlike long-term vector memory, this buffer is strictly chronological and is passed
directly to the LLM so the model maintains coherent conversational continuity.
"""

import json
from typing import List, Dict, Optional, Any
import logging

logger = logging.getLogger(__name__)


class ConversationMemory:
    """Manages short-term conversation turns for AURA, including user, assistant, and tool events."""

    def __init__(
        self,
        max_messages: int = 10,
        max_turns: Optional[int] = None,
    ) -> None:
        """Initialize short-term conversation memory.

        Args:
            max_messages: Maximum individual messages (user, assistant, tool) to keep.
            max_turns: Backward-compatible turn count (1 turn = 1 user + 1 assistant message).
                       If supplied, max_messages is set to max_turns * 2.
        """
        if max_turns is not None:
            self.max_messages = max_turns * 2
            self.max_turns = max_turns
        else:
            self.max_messages = max_messages
            self.max_turns = max_messages // 2

        self.history: List[Dict[str, Any]] = []

    def add_user_message(self, content: str) -> None:
        """Append a user message to conversation history.

        Args:
            content: The text spoken or typed by the user.
        """
        self.history.append({"role": "user", "content": str(content)})
        self._trim()

    def add_assistant_message(self, content: str) -> None:
        """Append an assistant response to conversation history.

        Args:
            content: The text generated by AURA.
        """
        self.history.append({"role": "assistant", "content": str(content)})
        self._trim()

    def add_tool_call(self, tool_name: str, parameters: Dict[str, Any]) -> None:
        """Append a tool invocation decision to conversation history.

        Args:
            tool_name: The name of the tool selected (e.g. 'calculator').
            parameters: Dictionary of arguments passed to the tool.
        """
        call_payload = {"tool": tool_name, "parameters": parameters}
        self.history.append({
            "role": "tool_call",
            "name": tool_name,
            "parameters": dict(parameters),
            "content": json.dumps(call_payload),
        })
        self._trim()

    def add_tool_result(self, tool_name: str, result: Dict[str, Any]) -> None:
        """Append a tool execution result to conversation history.

        Args:
            tool_name: The name of the executed tool.
            result: Structured dictionary returned by the tool.
        """
        self.history.append({
            "role": "tool",
            "name": tool_name,
            "result": dict(result),
            "content": json.dumps(result),
        })
        self._trim()

    def get_history(self, limit: Optional[int] = None) -> List[Dict[str, Any]]:
        """Retrieve conversation history in chronological order.

        Args:
            limit: Optional maximum number of recent messages to return.

        Returns:
            A list of message dictionaries with 'role', 'content', and optional metadata.
        """
        if limit is not None and limit > 0:
            return [dict(msg) for msg in self.history[-limit:]]
        return [dict(msg) for msg in self.history]

    def get_messages(self) -> List[Dict[str, Any]]:
        """Backward-compatible alias for get_history().

        Returns:
            List of message dictionaries.
        """
        return self.get_history()

    def get_context(self, max_messages: Optional[int] = None) -> List[Dict[str, Any]]:
        """Retrieve context messages ready to be supplied to the LLM.

        Args:
            max_messages: Optional limit overriding the default instance limit.

        Returns:
            Recent conversation history formatted for prompt injection.
        """
        limit = max_messages or self.max_messages
        return self.get_history(limit=limit)

    def format_context_text(self, max_messages: Optional[int] = None) -> str:
        """Format recent conversation history into a readable dialogue string.

        Args:
            max_messages: Optional limit on number of messages to format.

        Returns:
            Human-readable formatted dialogue string (e.g. 'User: ...\\nAssistant: ...').
        """
        messages = self.get_context(max_messages=max_messages)
        if not messages:
            return ""

        formatted_lines = []
        for msg in messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")
            if role == "user":
                formatted_lines.append(f"User: {content}")
            elif role == "assistant":
                formatted_lines.append(f"Assistant: {content}")
            elif role == "tool_call":
                tool_name = msg.get("name", "tool")
                formatted_lines.append(f"Tool Call ({tool_name}): {content}")
            elif role in ("tool", "tool_result"):
                tool_name = msg.get("name", "tool")
                formatted_lines.append(f"Tool Result ({tool_name}): {content}")
            else:
                formatted_lines.append(f"{role.capitalize()}: {content}")
        return "\n".join(formatted_lines)

    def clear(self) -> None:
        """Clear all conversation history."""
        self.history.clear()

    def clear_history(self) -> None:
        """Alias for clear()."""
        self.clear()

    def is_empty(self) -> bool:
        """Check if conversation memory contains no messages."""
        return len(self.history) == 0

    def __len__(self) -> int:
        """Return the number of messages currently in memory."""
        return len(self.history)

    def _trim(self) -> None:
        """Trim the oldest messages when the buffer exceeds max_messages.

        Uses a First-In, First-Out (FIFO) sliding window approach.
        """
        if self.max_messages is not None and self.max_messages > 0:
            if len(self.history) > self.max_messages:
                self.history = self.history[-self.max_messages:]
